# Generated by Django 5.0.1 on 2026-01-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Investor', '0034_evaluationcriterion_evaluationimage_evaluationscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=models.deletion.CASCADE, related_name='departments', to='The_Investor.branch')),
            ],
        ),
    ]
