# Generated by Django 5.0.1 on 2026-01-10 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Investor', '0035_branch_department'),
    ]

    def forwards(apps, schema_editor):
        Investor = apps.get_model('The_Investor', 'Investor')
        Branch = apps.get_model('The_Investor', 'Branch')
        Department = apps.get_model('The_Investor', 'Department')
        conn = schema_editor.connection
        cursor = conn.cursor()
        for inv in Investor.objects.all():
            bname = getattr(inv, 'branch', None)
            dname = getattr(inv, 'department', None)
            # normalize None/empty to empty-string so we create a placeholder Branch/Department
            bname_norm = bname if (bname is not None and bname != '') else ''
            dname_norm = dname if (dname is not None and dname != '') else ''
            # create/get branch and department rows (allow empty-string record)
            bobj, _ = Branch.objects.get_or_create(name=bname_norm)
            dobj, _ = Department.objects.get_or_create(name=dname_norm)
            cursor.execute(f"UPDATE The_Investor_investor SET branch = {int(bobj.id)}, department = {int(dobj.id)} WHERE id = {int(inv.id)}")

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='investor',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investors', to='The_Investor.branch'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investors', to='The_Investor.department'),
        ),
    ]
