# Generated by Django 5.0.1 on 2026-01-11 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Investor', '0037_add_department_branch_if_missing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المعيار')),
                ('max_observations', models.IntegerField(default=10, verbose_name='الحد الأقصى للملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'معيار التقييم',
                'verbose_name_plural': 'معايير التقييم',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='الشهر')),
                ('total_observations', models.IntegerField(default=0, editable=False, verbose_name='إجمالي الملاحظات')),
                ('total_points', models.IntegerField(default=0, editable=False, verbose_name='إجمالي النقاط')),
                ('max_possible_points', models.IntegerField(default=0, editable=False, verbose_name='أقصى نقاط ممكنة')),
                ('percentage', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5, verbose_name='النسبة المئوية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات عامة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='The_Investor.branch', verbose_name='الفرع')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='The_Investor.department', verbose_name='القسم')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='The_Investor.investor', verbose_name='الموظف')),
                ('evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المقيّم')),
            ],
            options={
                'verbose_name': 'التقييم الشهري',
                'verbose_name_plural': 'التقييمات الشهرية',
                'ordering': ['-month', 'branch', 'department', 'employee'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observations_count', models.IntegerField(default=0, verbose_name='عدد الملاحظات')),
                ('observations_details', models.TextField(blank=True, verbose_name='تفاصيل الملاحظات')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='The_Investor.evaluationcriteria', verbose_name='المعيار')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='The_Investor.monthlyevaluation', verbose_name='التقييم')),
            ],
            options={
                'verbose_name': 'تفاصيل التقييم',
                'verbose_name_plural': 'تفاصيل التقييمات',
                'ordering': ['criteria__order'],
                'unique_together': {('evaluation', 'criteria')},
            },
        ),
    ]
