# Generated by Django 5.0.1 on 2026-01-11 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('The_Investor', '0038_evaluationcriteria_monthlyevaluation_and_more'),
    ]

    operations = [
    ]
