# Generated by Django 5.0.1 on 2026-01-11 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('The_Investor', '0039_auto_20260111_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationdetail',
            name='criteria',
        ),
        migrations.AlterUniqueTogether(
            name='evaluationdetail',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='evaluationdetail',
            name='evaluation',
        ),
        migrations.RemoveField(
            model_name='monthlyevaluation',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='monthlyevaluation',
            name='department',
        ),
        migrations.RemoveField(
            model_name='monthlyevaluation',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='monthlyevaluation',
            name='evaluator',
        ),
        migrations.DeleteModel(
            name='EvaluationCriteria',
        ),
        migrations.DeleteModel(
            name='EvaluationDetail',
        ),
        migrations.DeleteModel(
            name='MonthlyEvaluation',
        ),
    ]
