# Generated by Django 5.0.1 on 2026-01-11 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Investor', '0040_remove_evaluationdetail_criteria_and_more'),
        ('The_Owner', '0040_projectstatus_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المعيار')),
                ('max_observations', models.IntegerField(default=10, verbose_name='الحد الأقصى للملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'معيار التقييم',
                'verbose_name_plural': 'معايير التقييم',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='الشهر')),
                ('total_observations', models.IntegerField(default=0, editable=False, verbose_name='إجمالي الملاحظات')),
                ('total_score', models.IntegerField(default=0, editable=False, verbose_name='إجمالي النقاط')),
                ('max_possible_score', models.IntegerField(default=0, editable=False, verbose_name='أقصى نقاط ممكنة')),
                ('percentage', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5, verbose_name='النسبة المئوية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات عامة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='The_Investor.department', verbose_name='القسم')),
                ('evaluator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='The_Owner.owner', verbose_name='المقيّم')),
            ],
            options={
                'verbose_name': 'تقييم القسم',
                'verbose_name_plural': 'تقييمات الأقسام',
                'ordering': ['-month', 'department'],
                'unique_together': {('department', 'month')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='الشهر')),
                ('total_observations', models.IntegerField(default=0, editable=False, verbose_name='إجمالي الملاحظات')),
                ('total_score', models.IntegerField(default=0, editable=False, verbose_name='إجمالي النقاط')),
                ('max_possible_score', models.IntegerField(default=0, editable=False, verbose_name='أقصى نقاط ممكنة')),
                ('percentage', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5, verbose_name='النسبة المئوية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات عامة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='The_Investor.investor', verbose_name='الموظف')),
                ('evaluator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='The_Owner.owner', verbose_name='المقيّم')),
            ],
            options={
                'verbose_name': 'تقييم الموظف',
                'verbose_name_plural': 'تقييمات الموظفين',
                'ordering': ['-month', 'employee'],
                'unique_together': {('employee', 'month')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observations_count', models.IntegerField(default=0, verbose_name='عدد الملاحظات')),
                ('description', models.TextField(blank=True, verbose_name='وصف الملاحظات')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='The_Owner.employeeevaluation', verbose_name='التقييم')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='The_Owner.evaluationcriterion', verbose_name='المعيار')),
            ],
            options={
                'verbose_name': 'ملاحظة تقييم الموظف',
                'verbose_name_plural': 'ملاحظات تقييم الموظف',
                'ordering': ['criterion__order'],
                'unique_together': {('evaluation', 'criterion')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeObservationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='employee_observations/%Y/%m/%d/', verbose_name='الصورة')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='وصف الصورة')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='The_Owner.employeeobservation', verbose_name='الملاحظة')),
            ],
            options={
                'verbose_name': 'صورة ملاحظة الموظف',
                'verbose_name_plural': 'صور ملاحظات الموظف',
            },
        ),
        migrations.CreateModel(
            name='EvaluationObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observations_count', models.IntegerField(default=0, verbose_name='عدد الملاحظات')),
                ('description', models.TextField(blank=True, verbose_name='وصف الملاحظات')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='The_Owner.evaluationcriterion', verbose_name='المعيار')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='The_Owner.departmentevaluation', verbose_name='التقييم')),
            ],
            options={
                'verbose_name': 'ملاحظة التقييم',
                'verbose_name_plural': 'ملاحظات التقييم',
                'ordering': ['criterion__order'],
                'unique_together': {('evaluation', 'criterion')},
            },
        ),
        migrations.CreateModel(
            name='ObservationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='evaluation_observations/%Y/%m/%d/', verbose_name='الصورة')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='وصف الصورة')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='The_Owner.evaluationobservation', verbose_name='الملاحظة')),
            ],
            options={
                'verbose_name': 'صورة الملاحظة',
                'verbose_name_plural': 'صور الملاحظات',
            },
        ),
    ]
