# Generated by Django 5.0.1 on 2026-01-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Owner', '0041_evaluationcriterion_departmentevaluation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationcriterion',
            name='criterion_type',
            field=models.CharField(choices=[('department', 'قسم'), ('employee', 'موظف')], default='department', max_length=20, verbose_name='نوع المعيار'),
        ),
    ]
